name: Backend CI

on:
  push:
    branches: [master, develop, develop-backend]
    paths:
      - "backend/**"
  pull_request:
    branches: [master, develop, develop-backend]
    paths:
      - "backend/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    uses: ./.github/workflows/reusable-ci.yml
    with:
      node-version: ${{ matrix.node-version }}
      lint-command: "npx eslint . --config eslint.config.js"
      test-command: "npm test" 