name: Mobile App CI

on:
  push:
    branches: [develop, master]
    paths:
      - "mobile-app/**"
      - "package-lock.json"
  pull_request:
    branches: [develop, master]
    paths:
      - "mobile-app/**"
      - "package-lock.json"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mobile-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            mobile-app/package-lock.json
      - name: Install dependencies (root)
        run: npm ci

      - name: Install mobile dependencies
        working-directory: ./mobile-app
        run: npm ci

      - name: Run mobile lint
        run: npm run mobile:lint

      - name: Run mobile unit tests
        run: npm run mobile:test

      - name: Install Expo CLI globally
        if: contains(github.event.head_commit.message, '[build-mobile]')
        run: npm install -g expo-cli

      - name: Prebuild native projects (SDK build)
        if: contains(github.event.head_commit.message, '[build-mobile]')
        working-directory: ./mobile-app
        run: npx expo prebuild --platform android --non-interactive --no-install --clean

      - name: Archive Android project as artifact
        if: contains(github.event.head_commit.message, '[build-mobile]')
        uses: actions/upload-artifact@v4
        with:
          name: mobile-android-sdk
          path: mobile-app/android/
          retention-days: 7 