name: Release Tag Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-release:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      build-command: "npm run build"
      # This command will run after the build is complete and artifacts are uploaded
      # We will create the zip archive here
    secrets: inherit

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-and-release.outputs.build-artifact-name }}
          path: dist

      - name: Create zip archive
        run: cd dist && zip -r ../cicdpipeline-${{ github.ref_name }}.zip .

      - name: Create GitHub Release from tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          bodyFile: CHANGELOG.md
          artifacts: ./cicdpipeline-${{ github.ref_name }}.zip
          generateReleaseNotes: false 