name: Release Tag Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write  # allow release publishing

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create zip archive
        run: cd dist && zip -r ../cicdpipeline-${{ github.ref_name }}.zip .

      - name: Create GitHub Release from tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          bodyFile: CHANGELOG.md
          artifacts: ./cicdpipeline-${{ github.ref_name }}.zip
          generateReleaseNotes: false 